import { AlertTriangle, Ban, BookOpen, CheckCircle2, MessageCircle, Repeat2, Shield, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Avatar } from '../components/Avatar'
import { api } from '../lib/api'
import { formatDateTime } from '../lib/constants'
import { ComplaintStatus, type AdminStats, type UserSummary } from '../lib/types'

type AdminUser = { id: string; email: string; displayName: string; city: string; isBlocked: boolean; createdAt: string }
type Complaint = { id: string; reporter: UserSummary; bookId?: string; bookTitle?: string; targetUser?: UserSummary; reason: string; status: ComplaintStatus; adminComment?: string; createdAt: string }

export function AdminPage() {
  const [stats, setStats] = useState<AdminStats | null>(null); const [users, setUsers] = useState<AdminUser[]>([]); const [complaints, setComplaints] = useState<Complaint[]>([]); const [tab, setTab] = useState<'complaints' | 'users'>('complaints')
  const load = () => Promise.all([api.get<AdminStats>('/admin/stats').then(({ data }) => setStats(data)), api.get<AdminUser[]>('/admin/users').then(({ data }) => setUsers(data)), api.get<Complaint[]>('/admin/complaints').then(({ data }) => setComplaints(data))])
  useEffect(() => { void load() }, [])
  const toggle = async (id: string) => { await api.patch(`/admin/users/${id}/toggle-block`); await load() }
  const updateComplaint = async (id: string, status: ComplaintStatus) => { const adminComment = window.prompt('Комментарий администратора (необязательно):') || ''; await api.patch(`/admin/complaints/${id}`, { status, adminComment }); await load() }

  return <div className="page admin-page"><div className="container"><div className="admin-heading"><div><span className="section-kicker">Служебный раздел</span><h1><Shield /> Администрирование</h1><p>Контроль пользователей, объявлений и жалоб сообщества.</p></div></div>{stats && <div className="admin-stats"><article><Users /><div><b>{stats.users}</b><span>Пользователей</span></div></article><article><BookOpen /><div><b>{stats.books}</b><span>Книг</span></div></article><article><Repeat2 /><div><b>{stats.exchanges}</b><span>Обменов</span></div></article><article><AlertTriangle /><div><b>{stats.openComplaints}</b><span>Открытых жалоб</span></div></article><article><MessageCircle /><div><b>{stats.messages}</b><span>Сообщений</span></div></article></div>}<div className="admin-tabs"><button className={tab === 'complaints' ? 'active' : ''} onClick={() => setTab('complaints')}>Жалобы <b>{complaints.filter(item => item.status === ComplaintStatus.Open).length}</b></button><button className={tab === 'users' ? 'active' : ''} onClick={() => setTab('users')}>Пользователи</button></div>
  {tab === 'complaints' ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Отправитель</th><th>Объект</th><th>Причина</th><th>Статус</th><th>Дата</th><th /></tr></thead><tbody>{complaints.map(item => <tr key={item.id}><td><div className="table-user"><Avatar name={item.reporter.displayName} size={34} /><span>{item.reporter.displayName}</span></div></td><td>{item.bookTitle || item.targetUser?.displayName || '—'}</td><td className="reason-cell">{item.reason}</td><td><span className={`complaint-status complaint-${item.status}`}>{['', 'Открыта', 'В работе', 'Решена', 'Отклонена'][item.status]}</span></td><td>{formatDateTime(item.createdAt)}</td><td><div className="table-actions">{item.status !== ComplaintStatus.Resolved && <button title="Решить" onClick={() => updateComplaint(item.id, ComplaintStatus.Resolved)}><CheckCircle2 /></button>}{item.status !== ComplaintStatus.Rejected && <button title="Отклонить" onClick={() => updateComplaint(item.id, ComplaintStatus.Rejected)}><Ban /></button>}</div></td></tr>)}</tbody></table></div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Пользователь</th><th>Email</th><th>Город</th><th>Регистрация</th><th>Состояние</th><th /></tr></thead><tbody>{users.map(item => <tr key={item.id}><td><div className="table-user"><Avatar name={item.displayName} size={34} /><span>{item.displayName}</span></div></td><td>{item.email}</td><td>{item.city}</td><td>{formatDateTime(item.createdAt)}</td><td><span className={item.isBlocked ? 'user-blocked' : 'user-active'}>{item.isBlocked ? 'Заблокирован' : 'Активен'}</span></td><td><button className="button button-ghost compact-button" onClick={() => toggle(item.id)}>{item.isBlocked ? 'Разблокировать' : 'Заблокировать'}</button></td></tr>)}</tbody></table></div>}
  </div></div>
}
